// Generated by CoffeeScript 1.3.3
(function() {

  Game.EventsDispatcher = (function() {

    function EventsDispatcher() {
      _.extend(this, Backbone.Events);
      this.initialize.apply(this, arguments);
    }

    EventsDispatcher.prototype.initialize = function() {};

    return EventsDispatcher;

  })();

}).call(this);
