// Generated by CoffeeScript 1.3.3
(function() {
  var AssetLibrary, Bitmap, ClassManager, Container, Ease, Entity, EventsDispatcher, HexTile, Particles, Scene, Settings, Shape, SheetData, SpriteSheet, SpriteSheetUtils, Ticker, Tween, Units,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Scene = Game.Scene, EventsDispatcher = Game.EventsDispatcher, Entity = Game.Entity, Units = Game.Units, HexTile = Game.HexTile, Particles = Game.Particles, AssetLibrary = Game.AssetLibrary, ClassManager = Game.ClassManager, SheetData = Game.SheetData;

  Shape = createjs.Shape, Ticker = createjs.Ticker, Ease = createjs.Ease, Tween = createjs.Tween, Container = createjs.Container, SpriteSheet = createjs.SpriteSheet, SpriteSheetUtils = createjs.SpriteSheetUtils, Bitmap = createjs.Bitmap;

  Settings = (function() {

    function Settings() {
      this.particles = false;
      this.particleEffects = false;
    }

    return Settings;

  })();

  Game.WingsOfLemuriaTactics = (function() {

    WingsOfLemuriaTactics.prototype.settings = new Settings;

    function WingsOfLemuriaTactics() {
      this.update = __bind(this.update, this);

      this.assetsReady = __bind(this.assetsReady, this);

      this.addUnit = __bind(this.addUnit, this);

      var canvas;
      canvas = document.querySelector('canvas#game');
      canvas.height = 450;
      this.particles = new Particles;
      this.scene = new Scene(canvas);
      this.scene.update = this.update;
      this.scene.pause();
      this.scene.addLayer('tiles');
      this.scene.addLayer('units');
      this.scene.addLayer('fx');
      this.fxLayer = this.scene.getLayer('fx');
      this.fxParticle = new Container;
      this.fade = new Shape;
      this.fade.graphics.beginFill('rgba(0,0,0,0.1)').drawRect(0, 0, canvas.width, canvas.height);
      this.fxLayer.addChild(this.fade, this.fxParticle);
      this.fxLayer.cache(0, 0, canvas.width, canvas.height);
      this.setTerrainPosition(5, 70);
      this.scene.terrain.x = 0;
      this.classes = new ClassManager;
      this.assets = new AssetLibrary;
      this.assets.add('background', 'images/background.png');
      this.assets.add('terrain', 'images/terrain.png');
      this.assets.add('elements', 'images/elements.png');
      this.classes.register('marine', Units.Marine);
      this.assets.add('marine', 'images/marine.png');
      this.classes.register('vanguard', Units.Vanguard);
      this.assets.add('vanguard', 'images/vanguard.png');
      this.assets.complete(this.assetsReady);
      this.assets.preload();
      return;
    }

    WingsOfLemuriaTactics.prototype.addUnit = function(code, attributes) {
      var asset, entity, sheetData;
      asset = this.assets.get(code);
      sheetData = SheetData.get(code, asset);
      entity = this.classes.create(code);
      entity.sheetData(sheetData);
      this.scene.getLayer('units').addChild(entity.sprite);
      return entity;
    };

    WingsOfLemuriaTactics.prototype.assetsReady = function() {
      var assetName, assetNames, spriteSheet, _i, _len;
      spriteSheet = new SpriteSheet(SheetData.elements(this.assets.get('elements')));
      assetNames = spriteSheet.getAnimations();
      for (_i = 0, _len = assetNames.length; _i < _len; _i++) {
        assetName = assetNames[_i];
        this.assets.add(assetName, SpriteSheetUtils.extractFrame(spriteSheet, assetName));
      }
      this.scene.setBackground(this.assets.get('background'));
      this.scene.setTerrain(this.assets.get('terrain'));
      this.setScene();
      return this.testUnit();
    };

    WingsOfLemuriaTactics.prototype.generateGrid = function() {
      var bitmap, column, columns, container, image, row, rows, tilePosition, _i, _j;
      rows = 7;
      columns = 8;
      container = new Container;
      image = this.assets.get('hex_bg');
      for (row = _i = 0; 0 <= rows ? _i <= rows : _i >= rows; row = 0 <= rows ? ++_i : --_i) {
        for (column = _j = 0; 0 <= columns ? _j <= columns : _j >= columns; column = 0 <= columns ? ++_j : --_j) {
          bitmap = new Bitmap(image);
          tilePosition = HexTile.position(column, row);
          bitmap.x = tilePosition.x;
          bitmap.y = tilePosition.y;
          container.addChild(bitmap);
        }
      }
      return this.scene.getLayer('tiles').addChild(container);
    };

    WingsOfLemuriaTactics.prototype.moveUnit = function(unit, tiles) {
      var hexTileImage, hexTiles, i, tileLayer, _i, _len;
      hexTiles = this.showTiles([[unit.tileX, unit.tileY]].concat(tiles));
      tileLayer = this.scene.getLayer('tiles');
      for (i = _i = 0, _len = hexTiles.length; _i < _len; i = ++_i) {
        hexTileImage = hexTiles[i];
        Tween.get(hexTileImage).wait(unit.walkDuration * i).to({
          alpha: 0,
          scaleX: 1.5,
          scaleY: 1.5
        }, 600).call(function() {
          return tileLayer.removeChild(this);
        });
      }
      return unit.walk(tiles);
    };

    WingsOfLemuriaTactics.prototype.setScene = function() {
      this.generateGrid();
      this.scene.play();
      return this;
    };

    WingsOfLemuriaTactics.prototype.setTerrainPosition = function(x, y) {
      this.scene.terrain.y = this.scene.getLayer('tiles').y = this.scene.getLayer('units').y = y;
      return this.scene.terrain.x = this.scene.getLayer('tiles').x = this.scene.getLayer('units').x = x;
    };

    WingsOfLemuriaTactics.prototype.showTiles = function(tiles, assetName) {
      var container, hexTiles, image;
      if (assetName == null) {
        assetName = 'hex_target';
      }
      image = this.assets.get(assetName);
      container = this.scene.getLayer('tiles');
      if (tiles instanceof Array) {
        hexTiles = [];
        _.each(tiles, function(tile) {
          var bitmap, tilePosition, x, y;
          x = tile.x, y = tile.y;
          bitmap = new Bitmap(image);
          tilePosition = HexTile.position(x, y, true);
          bitmap.x = tilePosition.x;
          bitmap.y = tilePosition.y;
          bitmap.tileX = x;
          bitmap.tileY = y;
          bitmap.regX = HexTile.WIDTH * 0.5;
          bitmap.regY = HexTile.HEIGHT * 0.5;
          container.addChild(bitmap);
          return hexTiles.push(bitmap);
        });
        return hexTiles;
      }
    };

    WingsOfLemuriaTactics.prototype.testUnit = function() {
      var data, hexTiles, particles, tiles, unit,
        _this = this;
      this.settings.particles = true;
      this.settings.particleEffects = true;
      unit = this.addUnit('marine');
      unit.walk(5, 0);
      data = {
        name: 'shield',
        asset: this.assets.get('shield'),
        total: 10,
        entity: unit
      };
      particles = this.particles.create(data.name, data.asset, data.total, data.entity);
      _.each(particles, function(particle) {
        _this.fxParticle.addChild(particle.bitmap);
        return particle.die = function(me) {
          return _this.fxParticle.removeChild(me.bitmap);
        };
      });
      return;
      tiles = HexTile.adjacent(unit.tileX, unit.tileY, 2);
      hexTiles = this.showTiles(tiles, 'hex_select');
      return _.each(hexTiles, function(hexTile, i) {
        return hexTile.onClick = function() {
          var adjacent, centerTile, tileX, tileY;
          centerTile = hexTile;
          tileX = centerTile.tileX, tileY = centerTile.tileY;
          return adjacent = HexTile.adjacent(tileX, tileY);
        };
      });
    };

    WingsOfLemuriaTactics.prototype.testUnits = function() {
      var column, columns, row, rows, unit, units, _i, _results;
      rows = 7;
      columns = 8;
      units = ['marine', 'vanguard'];
      _results = [];
      for (row = _i = 0; 0 <= rows ? _i <= rows : _i >= rows; row = 0 <= rows ? ++_i : --_i) {
        _results.push((function() {
          var _j, _results1;
          _results1 = [];
          for (column = _j = 0; 0 <= columns ? _j <= columns : _j >= columns; column = 0 <= columns ? ++_j : --_j) {
            unit = this.addUnit(units[Math.round(Math.random() * (units.length - 1))]);
            unit.walk(column, row);
            unit.play(Math.round(Math.random() * (unit.totalFrames() - 1)));
            if (Math.random() > 0.5) {
              _results1.push(unit.face('left'));
            } else {
              _results1.push(void 0);
            }
          }
          return _results1;
        }).call(this));
      }
      return _results;
    };

    WingsOfLemuriaTactics.prototype.update = function() {
      return;
      if (this.settings.particles) {
        this.particles.update();
        if (this.settings.particleEffects) {
          return this.updateParticleFx();
        }
      }
    };

    WingsOfLemuriaTactics.prototype.updateParticleFx = function() {
      this.fade.visible = !(this.fxParticle.visible = false);
      this.fxLayer.updateCache('destination-out');
      this.fade.visible = !(this.fxParticle.visible = true);
      return this.fxLayer.updateCache('lighter');
    };

    return WingsOfLemuriaTactics;

  })();

}).call(this);
